
set(Slicer_CMAKE_DIR "/home/leonardo/General_Sources/Slicer/CMake")
set(MIDAS_PACKAGE_URL "http://slicer.kitware.com/midas3")
set(MIDAS_PACKAGE_EMAIL "YOUR-MIDAS-LOGIN-NOTFOUND")
set(MIDAS_PACKAGE_API_KEY "YOUR-MIDAS-APIKEY-NOTFOUND")
set(CTEST_MODEL "Experimental")
set(Slicer_WC_REVISION "26905")
set(EXTENSION_NAME "TextureAnalysis")
set(EXTENSION_CATEGORY "Texture Analysis")
set(EXTENSION_ICONURL "http://www.example.com/Slicer/Extensions/TextureAnalysis.png")
set(EXTENSION_CONTRIBUTORS "Leonardo Machado (USP, RP.)")
set(EXTENSION_DESCRIPTION "This is an example of a simple extension")
set(EXTENSION_HOMEPAGE "http://slicer.org/slicerWiki/index.php/Documentation/Nightly/Extensions/TextureAnalysis")
set(EXTENSION_SCREENSHOTURLS "http://www.example.com/Slicer/Extensions/TextureAnalysis/Screenshots/1.png")
set(EXTENSION_ENABLED "1")
set(EXTENSION_OPERATING_SYSTEM "linux")
set(EXTENSION_ARCHITECTURE "amd64")
set(EXTENSION_WC_TYPE "local")
set(EXTENSION_WC_URL "NA")
set(EXTENSION_WC_REVISION "0")
set(EXTENSION_BINARY_DIR "/home/leonardo/Desktop/Modulos-Source/Modulos_to_Slicer/TextureProcessingExtension/TextureProcessing-Build/.")